Neos:
  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Flownative.WorkspacePreview:HashTokenRefresh':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Flownative\WorkspacePreview\Controller\.*'
          'Flownative.WorkspacePreview:TokenAuthenticator':
            provider: Flownative\TokenAuthentication\Security\HashTokenProvider
            token: Flownative\TokenAuthentication\Security\SessionStartingHashToken
            requestPatterns:
              'Neos.Neos:frontendControllers':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Neos\Neos\Controller\Frontend\.*'
              'Flownative.WorkspacePreview:HashtokenLogin':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Flownative\WorkspacePreview\Controller\.*'

    mvc:
      routes:
        'Flownative.WorkspacePreview': true

  Neos:
    userInterface:
      translation:
        autoInclude:
          'Flownative.WorkspacePreview':
            - Main
            - 'NodeTypes/*'
    Ui:
      resources:
        javascript:
          'Flownative.WorkspacePreview:Addons':
            resource: '${"resource://Flownative.WorkspacePreview/Public/LinkView/Plugin.js"}'

Flownative:
  TokenAuthentication:
    authenticationProviderName: 'Flownative.WorkspacePreview:TokenAuthenticator'
